name: "Scan with BlackDuck"
description: "Scans the project with BlackDuck"

inputs:
  blackduck_token:
    description: "The token to use for BlackDuck authentication"
    required: true
  github_token:
    description: "The token to use for GitHub authentication"
    required: true

runs:
  using: composite
  steps:
    - name: Print Action Start
      run: echo ">>>>> Starting Scan with BlackDuck Action; Not printing inputs as they might contain sensitive information."
      shell: bash

    - name: Get Major Version
      id: get-major-version
      run: |
        echo "MAJOR_VERSION=$(mvn help:evaluate -Dexpression=revision -q -DforceStdout)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Print Version Number
      run: echo "Version number is ${{ steps.get-major-version.outputs.MAJOR_VERSION }}"
      shell: bash

    - name: BlackDuck Scan
      uses: SAP/project-piper-action@master
      with:
        command: detectExecuteScan
        flags: \
          --githubToken=$GITHUB_token \
          --version=$PROJECT_VERSION
      env:
        PIPER_token: ${{ inputs.blackduck_token }}
        GITHUB_token: ${{ inputs.github_token }}
        SCAN_MODE: FULL
        PROJECT_VERSION: 1.0.1

    - name: Print Action End
      if: always()
      run: echo "<<<<< Finished Scan with BlackDuck Action"
      shell: bash
