steps:
  mavenBuild:
    verbose: false
    verify: true
    flatten: true

  detectExecuteScan:
    projectName: 'com.sap.cds.feature.attachments'
    groups:
      - 'CDSJAVA-OPEN-SOURCE'
    serverUrl: 'https://sap.blackducksoftware.com/'
    mavenExcludedScopes: [ "provided", "test" ]
    failOn: [ 'BLOCKER', 'CRITICAL', 'MAJOR' ]
    versioningModel: "major"
    detectTools: [ 'DETECTOR', 'BINARY_SCAN' ]
    scanProperties:
      - --detect.included.detector.types=MAVEN
      - --detect.excluded.directories='**/node_modules,**/*test*,**/localrepo,**/target/site,**/*-site.jar'
      - --detect.maven.excluded.modules=integration-tests,integration-tests/db,integration-tests/srv
      - --detect.maven.build.command='-pl !integration-tests,!integration-tests/db,!integration-tests/srv'
