steps:
  mavenBuild:
    verbose: false
    verify: true
    flatten: true

  detectExecuteScan:
    projectName: 'com.sap.cds.feature.attachments'
    groups:
      - 'CDSJAVA-OPEN-SOURCE'
    serverUrl: 'https://sap.blackducksoftware.com/'
    mavenExcludedScopes: [ "provided", "test" ]
    failOn: [ 'BLOCKER', 'CRITICAL', 'MAJOR' ]
    versioningModel: "major-minor"
    detectTools: [ 'DETECTOR', 'BINARY_SCAN' ]
    pomPath: './cds-feature-attachments/pom.xml'
    scanProperties:
      - --blackduck.signature.scanner.memory=4096
      - --blackduck.trust.cert=true
      - --detect.included.detector.types=MAVEN
      - --detect.excluded.directories='**/node_modules,**/*test*,**/localrepo,**/target/site,**/*-site.jar'
      - --detect.timeout=6000
      - --logging.level.com.synopsys.integration=DEBUG