name: Maven Deploy
description: "Deploys a Maven package to a repository."

inputs:
  repository-url:
    description: "The URL of the repository to upload to."
    required: true
  repository-id:
    description: "The ID of the repository to upload to."
    required: true
  user:
    description: "The user used for the upload."
    required: true
  password:
    description: "The password used for the upload."
    required: true
  pom-file-path:
    description: "The path to the pom file."
    required: false
    default: "pom.xml"
  jar-file-path:
    description: "The path to the jar file."
    required: false
    default: "target/*.jar"

runs:
  using: composite
  steps:
    - name: Publish package
      run: >
        mvn deploy:deploy-file 
            -DpomFile=${{ inputs.pom-file-path }} 
            -Dfile=${{ inputs.jar-file-path }} 
            -DrepositoryId=${{ inputs.repository-id }} 
            -Durl=${{ inputs.repository-url }} 
            -DrepositoryUsername=${{ inputs.user }} 
            -DrepositoryPassword=${{ inputs.password }}
      shell: bash
