name: Java CI with Maven

env:
  TARGET_ARTIFACT_NAME: 'service-target'
  TARGET_ARTIFACT_PATH: 'target'
  JAVA_VERSION: '17'
  DEPLOY_REPOSITORY_URL: 'https://common.repositories.cloud.sap/artifactory/'
  DEPLOY_REPOSITORY_ID: 'cap-java'
  SERVICE_POM: './cds-feature-attachments/pom.xml'
  JAR_NAME: 'cds-feature-attachments.jar'

on:
  release:
    branches: [ "main" ]
    types: [ "published" ]
#  push:
#    branches: [ "main" ]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update version
        uses: ./.github/actions/newrelease
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Upload Changed Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: root
          path: .
          retention-days: 1

  build:
    runs-on: ubuntu-latest
    needs: update-version
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: root

      - name: Build with Maven
        uses: ./.github/actions/build
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET_ARTIFACT_NAME }}
          path: cds-feature-attachments/target
          retention-days: 1

  deploy:
    name: Build and Deploy to Artifactory
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Start the deploy to Artifactory"
        name: deploy start

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.TARGET_ARTIFACT_NAME }}
          path: ${{ env.TARGET_ARTIFACT_PATH }}

      - name: Deploy with Maven
        uses: ./.github/actions/deploy
        with:
          user: ${{ secrets.DEPLOYMENT_USER }}
          password: ${{ secrets.DEPLOYMENT_PASS }}
          repository-url: ${{ env.DEPLOY_REPOSITORY_URL }}
          repository-id: ${{ env.DEPLOY_REPOSITORY_ID }}
          pom-file-path: ${{ env.SERVICE_POM }}
          jar-file-path: "./${{ env.TARGET_ARTIFACT_PATH }}/${{ env.JAR_NAME }}"

      - name: status
        run: echo "The job status is ${{ job.status }}"
