name: Java CI with Maven

on:
  release:
    branches: [ "main" ]
    types: [ "published" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 17, 21 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with Maven
        uses: ./.github/actions/build
        with:
          java-version: ${{ matrix.java-version }}

  deploy:
    name: Deploy to Artifactory
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Start the deploy to Artifactory"
        name: deploy start
      - name: deploy
        uses: SAP/project-piper-action@master
        with:
          help: sapCallStagingService
      - name: status
        run: echo "The job status is ${{ job.status }}"
