name: Java CI with Maven - deploy to OSS

env:
  JAVA_VERSION: '17'

on:
  release:
    types: [ "published" ]

jobs:

  blackduck:
    name: "Scan + Build + Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      # - name: "Scan With Black Duck"
      #   uses: ./.github/actions/scan-with-blackduck
      #   with:
      #     blackduck_token: ${{ secrets.BLACK_DUCK_TOKEN }}
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Update version
      #   uses: ./.github/actions/newrelease
      #   with:
      #     java-version: ${{ env.JAVA_VERSION }}

      - name: Build with Maven
        uses: ./.github/actions/build
        with:
          java-version: ${{ env.JAVA_VERSION }}
          mutation-testing: 'false'

      - name: Deploy with Maven
        uses: ./.github/actions/deploy-release
        with:
          user: ${{ secrets.OSSRH_SONATYPE_ORG_API_USER }}
          password: ${{ secrets.OSSRH_SONATYPE_ORG_API_PASSWD }}
          profile: ${{ secrets.OSSRH_SONATYPE_ORG_PROFILE_ID }}
          pgp-pub-key: ${{ secrets.PGP_PUBKEY_ID }}
          pgp-private-key: ${{ secrets.PGP_PRIVATE_KEY }}
          pgp-passphrase: ${{ secrets.PGP_PASSPHRASE }}
          revision: 1.0.3
