name: Java Build with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix: 
        java-version: [17, 21]

    steps:
      - name: Build with Maven
        uses: ./.github/actions/build.yaml
        with:
          java-version: ${{ matrix.java-version }}
